### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by dudunegrinhu** [sintret/yii2-todolist#1]
Username and password is not working on demo

**Comment by sintret** [comment]
username : admin
password :123456

refer to http://sintret.com/adiadrian/

**Comment by dudunegrinhu** [comment]
Thanks. Nice extension, do you know why the todo list edit and delete button doesn't work?

**Comment by sintret** [comment]
oops its not finished yet that. you can add edit and delete its self. btw i am still busy and maybe next week i will update soon. 

thanks
